version: '3.8'
services:
  spring-batch-database:
    container_name: spring-batch-database
    image: mysql:8.0.31
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'db'
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: on-failure
    networks:
      - spring-batch-network
networks:
  spring-batch-network:
    driver: bridge
    name: spring-batch-network
